name: Publish to pypi
on:
    push:
        branches: [ main ]
        tags: [ -v* ]
jobs:
    publish-to-pypi:
        runs-on: ubuntu-20.04
        steps:
            -   name: build-distribution
                uses: actions/setup-python@v2
                with:
                    python-version: '3.9'
            -   run: |
                    python setup.py sdist
            -   name: publish
                uses: pypa/gh-action-pypi-publish@release/v1
                with:
                    user: __token__
                    password: ${{ secrets.PYPI_API_TOKEN_ORTHANC_SERVER_EXTENSIONS }}
