name: Publish to pypi
on:
    push:
        branches: [ main ]
if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
jobs:
    publish-to-pypi:
        steps:
            -   uses: pypa/gh-action-pypi-publish@release/v1
                with:
                    user: __token__
                    password: ${{ secrets.PYPI_API_TOKEN_ORTHANC_SERVER_EXTENSIONS }}
